[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "pj-py"
dynamic = ["version"]
description = "SolveIT-friendly tool to make project repos a bit easier to manage"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "Apache-2.0"}
authors = [{name = "Kit Ledru", email = "kit@ledru.dev"}]
keywords = ['nbdev', 'jupyter', 'notebook', 'python']
classifiers = ["Natural Language :: English", "Intended Audience :: Developers", "Development Status :: 3 - Alpha", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3 :: Only"]
dependencies = []

[project.urls]
Repository = "https://github.com/1iis/pj"
Documentation = "https://1iis.github.io/pj"

[project.entry-points.nbdev]
pj = "pj._modidx:d"

[tool.setuptools.dynamic]
version = {attr = "pj.__version__"}

[tool.setuptools.packages.find]
include = ["pj"]

[tool.nbdev]
title = 'pj-py'
