"""`Project` & friends"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['set_api', 'get_api', 'set_verbosity', 'Result', 'Lines', 'FileList', 'Project', 'new', 'pjtype', 'solveit_url']

# %% ../nbs/00_core.ipynb #647bfd8d
from pathlib import Path
import os, re, subprocess, time
from fastcore.basics import store_attr, patch
from fastcore.foundation import L
from urllib.parse import quote
from fastgit import Git
from ghapi.all import GhApi
from nbdev.release import release_pypi, push_release, bump_version

# %% ../nbs/00_core.ipynb #7549e804
_default_api = None  # Module-level API holder

# %% ../nbs/00_core.ipynb #d3065b47
def set_api(api: GhApi|None):
    """Set the default GhApi instance for all Project instances."""
    global _default_api; _default_api = api

# %% ../nbs/00_core.ipynb #684983e8
def get_api() -> GhApi|None:
    """Get the current default GhApi instance."""
    return _default_api

# %% ../nbs/00_core.ipynb #d6c5f33b
_verbosity = 1  # 0=quiet, 1=normal, 2=verbose
def set_verbosity(v: int): global _verbosity; _verbosity = v

# %% ../nbs/00_core.ipynb #9f97c410
_solveit_domain = os.environ.get('PRIVATE_DOMAIN', '') if os.environ.get('IN_SOLVEIT') else ''

# %% ../nbs/00_core.ipynb #438a8eaf
class Result:
    def __init__(self, val, ok: bool=True, msg: str=''): store_attr()
    def __repr__(self): return repr(self.val)
    def __getattr__(self, k):
        if k in ('val', 'ok', 'msg') or k.startswith('_'): raise AttributeError(k)
        return getattr(self.val, k)
    def _repr_markdown_(self):
        if _verbosity == 0: return ''
        return f"{'✓' if self.ok else '✗'} {self.msg}"

# %% ../nbs/00_core.ipynb #7a277093
class Lines(L):
    """L subclass with markdown repr that joins lines."""
    # def _repr_markdown_(self): return '\n'.join(str(x) for x in self) or "Empty."
    def _repr_markdown_(self): return f"```\n{chr(10).join(str(x) for x in self)}\n```" if self else "Empty."


# %% ../nbs/00_core.ipynb #369f6519
class FileList(Lines):
    def __init__(self, items, base_path, domain=None):
        super().__init__(items)
        self.base_path, self.domain = base_path, domain
    
    def _repr_markdown_(self):
        def _fmt(f):
            rel = f.relative_to(self.base_path)
            if self.domain and f.suffix == '.ipynb':
                rel_home = f.resolve().relative_to(Path.home()).with_suffix('')
                return f"- <a href='https://{self.domain}.solve.it.com/dialog_?name={quote(str(rel_home))}' target='_blank'>`{rel.with_suffix('')}`</a>"
            return f"- `{rel}`"
        return '\n'.join(_fmt(f) for f in self) or "No files found."

# %% ../nbs/00_core.ipynb #ecbf3640
def _rename_template(path: Path, name: str, desc: str | None = None) -> None:
    """Rename template placeholders (my_package, my-package) to actual project name."""
    pkg = name.replace('-', '_')
    src = path / 'src' / 'my_package'
    dst = path / 'src' / pkg
    if src.exists(): src.rename(dst)
    for f in [path / 'pyproject.toml', path / 'tests' / 'test_main.py']:
        if not f.exists(): continue
        txt = f.read_text(encoding='utf-8')
        txt = txt.replace('my-package', name).replace('my_package', pkg)
        if desc is not None:
            txt = txt.replace('"One thing, done well."', f'"{desc}"')
        f.write_text(txt)

# %% ../nbs/00_core.ipynb #57c638c6
class Project:
    """Manage a project's lifecycle: init, sync, ship."""
    def __init__(self, path: str|Path, api: GhApi|None=None, org: str|None=None):
        store_attr()  # auto-store params as self.x
        self.path = Path(path)
        self.api = api or _default_api or GhApi()
        self.g = Git(self.path)
        self.owner, self.repo = self._parse_remote()
        if org: self.owner = org

# %% ../nbs/00_core.ipynb #af821a4f
@classmethod
def new(cls, 
        name: str,                   # Repository name
        path: str|Path | None=None,  # Local path (defaults to ./name)
        api: GhApi     | None=None,  # GitHub API instance
        org: str       | None=None,  # Organization (overrides authenticated user)
        desc: str      | None=None,  # Repository description
        private: bool=True,          # Create private repository
        nbdev: bool=False,           # Initialize as nbdev project
        template: str|None=None,     # Template name (e.g. "py"), or "owner/repo"
        template_org: str="1iis",    # Template owner (used if template has no "/")
) -> 'Project':
    """Create a new GitHub repo, clone it, and return a Project instance."""
    api = api or _default_api or GhApi()
    owner = org or api.users.get_authenticated().login
    path = Path(path or '.') / name

    if template:
        if nbdev:
            import warnings
            warnings.warn("template overrides nbdev=True; ignoring nbdev")
        if '/' in template:
            tmpl_owner, tmpl_repo = template.split('/', 1)
        else:
            tmpl_owner, tmpl_repo = template_org, template
        api.repos.create_using_template(
            tmpl_owner, tmpl_repo,
            name=name, description=desc or '',
            private=private,
        )
        Git('.').clone(f"git@github.com:{owner}/{name}.git", str(path))
        _rename_template(path, name, desc)
        subprocess.run(['uv', 'sync', '--group', 'dev'], cwd=path)
    else:
        if org: api.repos.create_in_org(org, name=name, description=desc or '', private=private)
        else: api.repos.create_for_authenticated_user(name=name, description=desc or '', private=private)
        Git('.').clone(f"git@github.com:{owner}/{name}.git", str(path))
        subprocess.run(['nbdev_install_hooks'], cwd=path, check=True)
        if nbdev: subprocess.run(['nbdev_new', '--repo', name, '--user', owner], cwd=path, check=True)
    
    proj = cls(path, api=api, org=org)
    if nbdev and not template: proj.dark_theme()
    proj.g.add('-A')
    proj.g.commit(m='Initial commit', mute_errors=True)
    push_ok = True
    try:
        proj.g.push()
    except Exception as e:
        push_ok = False
        if _verbosity >= 1: print("⚠️ Push failed (likely temporary GitHub issue).\n   Repo created successfully. Retry: `p.push()`")
    
    if nbdev and not template and push_ok: proj.setup_pages()
    if os.environ.get('IN_SOLVEIT'): display(proj)
    if _verbosity >= 1: print(f"✓ Project '{name}' created successfully.")
    return proj

Project.new = new

# %% ../nbs/00_core.ipynb #ade78046
@patch
def sync(self: Project,
         msg: str="sync"  # Git commit message
) -> Result:
    """Commit all, pull --rebase, push. Runs nbdev_prepare if nbdev project."""
    if self._detect_type() == 'nbdev' and os.environ.get('IN_SOLVEIT'): subprocess.run(['nbdev_prepare'], cwd=self.path, check=True)
    self.g.add('-A')
    self.g.commit(m=msg, mute_errors=True)
    self.g.pull(rebase=True)
    self.g.push()
    return Result(msg, msg=f"Synced: {msg}.")

# %% ../nbs/00_core.ipynb #16cc163f
@patch
def ship(self: Project, 
         part: int=2,              # Version part to bump: 0=major, 1=minor, 2=patch
         dry_run: bool=False,      # Show what would happen without executing
         force: bool=False,        # Ship even with uncommitted changes
         pypi: bool=False,         # Upload to PyPI
         quiet: bool=False         # Suppress build output
) -> Result:
    """Bump version, build, upload to PyPI, tag, and create GitHub release."""
    ptype = self._detect_type()
    
    if self.g.status('--porcelain') and not force:
        raise RuntimeError("Uncommitted changes! Commit first or use force=True.")
    
    version = self._get_version()
    if version and ptype != 'other':
        new_version = bump_version(version, part)
        if not dry_run: self._set_version(new_version)
        version = new_version
    
    tag = f"v{version}" if version else self._next_tag()
    if dry_run: return Result(tag, msg=f"Dry run: {tag}.")
    
    if pypi and ptype in ('nbdev', 'python'):
        os.chdir(self.path)
        release_pypi(quiet=quiet)
    
    self.sync(msg=f"Release {tag}")
    if ptype == 'nbdev':
        os.chdir(self.path)
        push_release()
    else:
        self.g.tag(tag, a=True, m=f"Release {tag}")
        self.g.push(tags=True)
        self.api.create_release(owner=self.owner, repo=self.repo, tag_name=tag, generate_release_notes=True)
    
    if ptype == 'nbdev': self._ensure_pages()
    return Result(tag, msg=f"Shipped: {tag}.")

# %% ../nbs/00_core.ipynb #c6e4c8b9
@patch
def ls(self: Project, 
       pattern: str = '',      # Shortcut ('nbs', 'py') or regex
       exclude: list = None    # Paths to exclude
) -> FileList:
    """List files in repo, optionally filtered. Returns FileList."""
    shortcuts = {'nbs': r'\.ipynb$', 'py': r'\.py$'}
    regex = shortcuts.get(pattern, pattern) or None
    exclude = exclude or ['.git', '__pycache__', '.ipynb_checkpoints', '_proc', r'^tmpfgm_.*\.ipynb$']
    
    files = sorted(f for f in self.path.rglob('*') if f.is_file())
    for ex in exclude: files = [f for f in files if not re.search(ex, str(f.relative_to(self.path)))]
    if regex: files = [f for f in files if re.search(regex, str(f))]
    
    return FileList(files, self.path, _solveit_domain)


# %% ../nbs/00_core.ipynb #127dc5a2
@patch
def __getattr__(self: Project, k):
    """Forward unknown methods to Git instance, wrapping list outputs in Lines."""
    if k.startswith('_'): raise AttributeError(k)
    attr = getattr(self.g, k)
    if not callable(attr): return attr
    return lambda *a, **kw: Lines(r) if isinstance(r := attr(*a, **kw), list) else r


# %% ../nbs/00_core.ipynb #50b01d69
@patch
def __dir__(self: Project): return super().__dir__() + dir(self.g)

# %% ../nbs/00_core.ipynb #0300598b
@patch
def _repr_markdown_(self: Project): return f"""Project info

Owner: **<a href="https://github.com/{self.owner}" target="_blank">{self.owner}</a>**  
Repo: **<a href="https://github.com/{self.owner}/{self.repo}" target="_blank">`{self.repo}`</a>**  

Type: {self._detect_type()}  
{f'Docs: <a href="https://{self.owner}.github.io/{self.repo}" target="_blank">https://{self.owner}.github.io/{self.repo}</a>' if self._detect_type() == 'nbdev' else ""}  

{f"📁 SolveIT: <a href='{self.solveit_url.rsplit('/', 1)[0]}' target='_blank'><code>[{self.path.parent.resolve()}/]</code></a>**<code><a href='{self.solveit_url}' target='_blank'>{self.path.name}</code></a>**" if _solveit_domain else ""}  
"""

# %% ../nbs/00_core.ipynb #f4eaad25
@patch
def _parse_remote(self: Project):
    """Parse (owner, repo) from git remote URL, or (None, None) if not found."""
    try:
        url = self.g.remote('get-url', 'origin').replace('.git', '')
        parts = url.split('/')
        return parts[-2].split(':')[-1], parts[-1]  # handles git@github.com:owner/repo
    except: return None, None

# %% ../nbs/00_core.ipynb #f886e8bb
@patch
def _detect_type(self: Project):
    """Detect project type: 'nbdev', 'python', or 'other'."""
    if (self.path / 'settings.ini').exists(): return 'nbdev'
    if (self.path / 'pyproject.toml').exists(): return 'python'
    return 'other'

# %% ../nbs/00_core.ipynb #9d2c9388
@property
def pjtype(self: Project): return self._detect_type()

Project.pjtype = pjtype

# %% ../nbs/00_core.ipynb #fac4e609
@property
def solveit_url(self: Project):
    if not _solveit_domain: return None
    rel_path = str(self.path.resolve()).replace('/app/data/', '').replace('/', '%2F')
    return f"https://{_solveit_domain}.solve.it.com/?at={rel_path}"

Project.solveit_url = solveit_url

# %% ../nbs/00_core.ipynb #cfc03981
@patch
def _get_version(self: Project):
    """Extract version from settings.ini (nbdev) or pyproject.toml (standard)."""
    if (p := self.path / 'settings.ini').exists():
        for line in p.read_text().splitlines():
            if line.startswith('version'): return line.split('=')[1].strip()
    if (p := self.path / 'pyproject.toml').exists():
        import tomllib
        return tomllib.loads(p.read_text()).get('project', {}).get('version')
    return None

# %% ../nbs/00_core.ipynb #81d00a9e
@patch
def _set_version(self: Project, version: str):
    """Write version to settings.ini or pyproject.toml."""
    if (p := self.path / 'settings.ini').exists():
        p.write_text(re.sub(r'^version\s*=.*$', f'version = {version}', p.read_text(), flags=re.MULTILINE))
    elif (p := self.path / 'pyproject.toml').exists():
        p.write_text(re.sub(r'^version\s*=\s*"[^"]*"', f'version = "{version}"', p.read_text(), flags=re.MULTILINE))

# %% ../nbs/00_core.ipynb #29c5abe1
@patch  
def _next_tag(self: Project) -> str:
    """Generate next tag for non-versioned projects (v1, v2, ...)."""
    tags = self.api.list_tags(owner=self.owner, repo=self.repo)
    nums = [int(t.name[1:]) for t in tags if t.name.startswith('v') and t.name[1:].isdigit()]
    return f"v{max(nums, default=0) + 1}"

# %% ../nbs/00_core.ipynb #e00c9b7d
@patch
def _ensure_pages(self: Project, timeout: int=120, poll_interval: int=10) -> bool:
    """Ensure GitHub Pages is configured for gh-pages branch. Returns True if successful."""
    try:  # Check current config
        pages = self.api.repos.get_pages(owner=self.owner, repo=self.repo)
        if pages.source.branch == 'gh-pages': return True
    except: pass  # Pages not enabled yet
    deadline = time.time() + timeout  # Wait for gh-pages branch to exist
    if _verbosity >= 1: print(f"Waiting for GitHub Actions to create branch: 'gh-pages'. (timeout: {timeout}s)")
    while time.time() < deadline:
        branches = [b.name for b in self.api.repos.list_branches(owner=self.owner, repo=self.repo)]
        if 'gh-pages' in branches: break
        time.sleep(poll_interval)
    else: return False  # Timed out
    
    try:  # Configure Pages
        self.api.repos.create_pages_site(owner=self.owner, repo=self.repo, source={'branch': 'gh-pages', 'path': '/'})
        return True
    except:
        try:  # Maybe already exists, just needs update
            self.api.repos.update_information_about_pages_site(
                owner = self.owner, repo = self.repo, source = {'branch': 'gh-pages', 'path': '/'} )
            return True
        except: return False

# %% ../nbs/00_core.ipynb #bb29d841
@patch
def setup_pages(self: Project) -> Result:
    """Manually configure GitHub Pages. Useful for debugging."""
    if self._ensure_pages(): return Result(True, msg=f"Pages configured: https://{self.owner}.github.io/{self.repo}/")
    return Result(False, ok=False, msg="⚠️  Timeout waiting for gh-pages branch. Run `p.setup_pages()` manually after Actions complete.")


# %% ../nbs/00_core.ipynb #a81bb2b8
#| echo: false
_dark_scss = '''/*-- scss:defaults --*/
// Quarto adaptation for nbdev theme

// Base document colors for dark mode
$body-bg: #181818;
$body-color: #ccc;
$link-color: #75AADB;

// Code blocks
$code-block-bg-alpha: -.9;

// Navbar
$navbar-bg: #2a2a2a;

/*-- scss:rules --*/

// Fix cell output text visibility in dark mode
.cell-output,
.cell-output-display {
  color: #ccc;
}

.cell-output pre {
  color: #ccc;
  background-color: #1e1e1e;
}

// Ensure code output is visible
.cell-output > pre code,
.cell-output-stdout pre {
  color: #ccc;
}

// Fix inline code in dark mode
code:not(pre > code) {
  background-color: #2a2a2a !important;
  color: #ab8dff;
}

// Fix blockquote code blocks in dark mode
blockquote pre,
blockquote pre code {
  color: #ccc;
  background-color: #1e1e1e;
}

blockquote {
  border-left-color: #555;
  color: #bbb;
}
'''

# %% ../nbs/00_core.ipynb #80f321e4
@patch
def dark_theme(self: Project) -> Result:
    """Apply dark mode theme to nbdev docs."""
    nbs = self.path / 'nbs' # nbdev standard notebook dir
    if not nbs.exists(): raise FileNotFoundError(f"No nbs/ directory in {self.path}")
    quarto_yml = nbs / '_quarto.yml'
    text = re.sub(r'(\s+)theme:\s*cosmo', r'\n    theme:\n      light: cosmo\n      dark: [cosmo, dark.scss]', quarto_yml.read_text())

    quarto_yml.write_text(text)
    (nbs / 'dark.scss').write_text(_dark_scss)
    return Result(True, msg="Dark theme applied.")
